[package]
name = "continuum-ai"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
tracing.workspace = true
image = { version = "0.25", features = ["jpeg", "png"] }
continuum-transport = { path = "../continuum-transport" }
chrono = "0.4"
