[package]
name = "continuum-core"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[features]
default = []
